#　コピペはここから
name: Deploy to Firebase Hosting on PR
"on": pull_request

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # node_modulesフォルダーをキャッシュすることによってビルド時間が短縮されます
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      # ここで--prefer-offlineフラグでキャッシュされたnode_modulesフォルダーを使われます
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      # run: npm ci --prefer-offline

      - name: Build and deploy
        run: yarn build
      # run: npm build
      # コピペはここまで
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_BLOG_C6996 }}"
          projectId: my-blog-c6996
